// IAEngine: 2D Game Engine by IA
// Copyright (C) 2025 IASoft (PVT) LTD (oss@iasoft.dev)
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

#include <IAEngine/Engine.hpp>
#include <IAEngine/Nodes/Node2D.hpp>

namespace ia::iae
{
    Node2D::Node2D(IN CONST String &name) : INode(name)
    {
    }

    Node2D::~Node2D()
    {
        for(auto& t: m_components)
            delete t;
    }

    VOID Node2D::Draw()
    {
        for(auto& t: m_components)
            t->Draw();
        for(auto& t: m_children)
            t->Draw();
    }

    VOID Node2D::DebugDraw()
    {
        for(auto& t: m_components)
            t->DebugDraw();
        for(auto& t: m_children)
            t->DebugDraw();
    }

    VOID Node2D::Update()
    {
        for(auto& t: m_components)
            t->Update();
        for(auto& t: m_children)
            t->Update();
    }

    VOID Node2D::FixedUpdate()
    {
        for(auto& t: m_components)
            t->FixedUpdate();
        for(auto& t: m_children)
            t->FixedUpdate();
    }
} // namespace ia::iae